# Generated by Django 3.0.8 on 2020-08-13 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jmxs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_name', models.CharField(max_length=100, verbose_name='csv文件名称')),
                ('csv', models.CharField(max_length=200, verbose_name='csv文件路径')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
                ('jmx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmxs.Jmxs')),
            ],
            options={
                'verbose_name': 'CSV文件',
                'verbose_name_plural': 'CSV文件',
            },
        ),
    ]
