# Generated by Django 3.0.8 on 2020-08-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvs',
            name='csv_name',
        ),
    ]
