# Generated by Django 3.0.8 on 2020-08-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200820_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomstr', models.CharField(max_length=20, verbose_name='随机字符串')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks', verbose_name='任务流水id')),
            ],
        ),
    ]
