# Generated by Django 3.0.8 on 2020-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='randomstr',
            field=models.CharField(max_length=30, verbose_name='随机字符串'),
        ),
    ]
