# Generated by Django 3.0.8 on 2020-08-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200820_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskflow',
            name='celery_task',
            field=models.CharField(default='aa', max_length=40, verbose_name='celery任务的id'),
        ),
    ]
