# Generated by Django 3.0.8 on 2020-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskflow_celery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='celery_task',
            field=models.CharField(max_length=40, verbose_name='celery任务的id'),
        ),
    ]
