# Generated by Django 3.0.8 on 2020-08-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200821_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskflow',
            old_name='celery_task',
            new_name='celery_task_id',
        ),
    ]
