# Generated by Django 3.0.8 on 2020-08-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0010_auto_20200813_1420'),
        ('tasks', '0007_auto_20200821_1004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasksdetails',
            unique_together={('task', 'jmx')},
        ),
    ]
