# Generated by Django 3.0.8 on 2020-08-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200821_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskflow',
            options={'verbose_name': '任务流水表', 'verbose_name_plural': '任务流水表'},
        ),
    ]
