# Generated by Django 3.0.8 on 2020-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200823_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskflow',
            name='task_status',
            field=models.IntegerField(default=0, verbose_name='任务流水状态'),
        ),
    ]
