# Generated by Django 3.0.8 on 2020-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskflow_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='randomstr',
            field=models.CharField(max_length=50, verbose_name='随机字符串'),
        ),
    ]
