# Generated by Django 3.0.8 on 2020-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_flowtaskaggregatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowtaskaggregatereport',
            name='add_time',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
