# Generated by Django 3.0.8 on 2020-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_flowtaskaggregatereport_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowtaskaggregatereport',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
