# Generated by Django 3.0.8 on 2020-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jmxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmx_name', models.CharField(max_length=50, verbose_name='jmx文件名称')),
                ('jmx_path', models.FileField(upload_to='jmx/', verbose_name='jmx存放路径')),
                ('jmx_setup_thread_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='setup线程组名称')),
                ('sample_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='线程组单sample请求的url地址')),
                ('sample_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='线程组单sample请求的method')),
                ('sample_params', models.CharField(blank=True, max_length=1000, null=True, verbose_name='线程组单sample请求的query参数')),
                ('sample_raw', models.CharField(blank=True, max_length=5000, null=True, verbose_name='线程组单sample请求的query参数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'jmx文件信息',
                'verbose_name_plural': 'jmx文件信息',
            },
        ),
    ]
