# Generated by Django 3.0.8 on 2020-08-13 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jmxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmx', models.CharField(max_length=200, verbose_name='jmx存放路径')),
                ('jmx_setup_thread_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='setup线程组名称')),
                ('sampler_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='单sampler的名称')),
                ('sampler_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='单sample请求的url地址')),
                ('sampler_info', models.CharField(max_length=5000, verbose_name='线程组下sampler请求和参数信息')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'jmx文件信息',
                'verbose_name_plural': 'jmx文件信息',
            },
        ),
    ]
