# Generated by Django 3.0.8 on 2020-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0002_auto_20200813_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxs',
            name='sampler_info',
            field=models.CharField(max_length=5000, verbose_name='线程组下sampler请求和参数信息'),
        ),
    ]
