# Generated by Django 3.0.8 on 2020-08-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0002_jmxs_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jmxs',
            name='add_user',
        ),
    ]
