# Generated by Django 3.0.8 on 2020-08-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0003_remove_jmxs_add_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmxs',
            old_name='jmx_path',
            new_name='jmx',
        ),
    ]
