# Generated by Django 3.0.8 on 2020-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0003_auto_20200813_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxs',
            name='sampler_info',
            field=models.TextField(verbose_name='线程组下sampler请求和参数信息'),
        ),
    ]
