# Generated by Django 3.0.8 on 2020-08-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0005_auto_20200813_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmxs',
            old_name='sampler_info',
            new_name='samplers_info',
        ),
    ]
