# Generated by Django 3.0.8 on 2020-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0006_remove_jmxs_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxs',
            name='jmx',
            field=models.CharField(max_length=200, verbose_name='jmx存放路径'),
        ),
        migrations.AlterField(
            model_name='jmxs',
            name='jmx_name',
            field=models.CharField(max_length=100, verbose_name='jmx文件名称'),
        ),
        migrations.AlterField(
            model_name='jmxs',
            name='jmx_setup_thread_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='setup线程组名称'),
        ),
    ]
