# Generated by Django 3.0.8 on 2020-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0007_auto_20200813_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxs',
            name='samplers_info',
            field=models.TextField(verbose_name='线程组下sampler请求和参数信息'),
        ),
    ]
