# Generated by Django 3.0.8 on 2020-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0008_auto_20200813_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmxs',
            name='mulit_samplers',
            field=models.BooleanField(default=True, verbose_name='判断是否是多个sampler的jmx'),
        ),
    ]
