# Generated by Django 3.0.8 on 2020-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0009_jmxs_mulit_samplers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmxs',
            old_name='mulit_samplers',
            new_name='is_mulit_samplers',
        ),
    ]
