# Generated by Django 3.0.8 on 2020-09-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0011_auto_20200823_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='JmxThreadGroupChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='线程组子类的名称')),
                ('child_type', models.CharField(choices=[('sampler', 'http请求'), ('csv', 'CSV数据文件设置')], default='sampler', max_length=10, verbose_name='子类的类型')),
                ('child_info', models.TextField(verbose_name='线程组子类的信息')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('jmx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmxs.Jmxs')),
            ],
        ),
    ]
