# Generated by Django 3.0.8 on 2020-09-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0012_jmxthreadgroupchildren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jmxs',
            name='samplers_info',
        ),
    ]
