# Generated by Django 3.0.8 on 2020-09-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0016_auto_20200902_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jmxs',
            name='is_mulit_samplers',
        ),
        migrations.RemoveField(
            model_name='jmxs',
            name='sampler_name',
        ),
        migrations.RemoveField(
            model_name='jmxs',
            name='sampler_url',
        ),
    ]
