# Generated by Django 3.0.8 on 2020-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0017_auto_20200902_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmxthreadgroupchildren',
            name='child_thread',
            field=models.CharField(choices=[('sampler', 'http请求'), ('csv', 'CSV数据文件设置')], default='thread', max_length=10, verbose_name='所在线程组类型'),
        ),
    ]
