# Generated by Django 3.0.8 on 2020-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0018_jmxthreadgroupchildren_child_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jmxs',
            name='jmx_setup_thread_name',
        ),
        migrations.AlterField(
            model_name='jmxthreadgroupchildren',
            name='child_thread',
            field=models.CharField(choices=[('thread', '普通线程组'), ('setup', 'setup线程组')], default='thread', max_length=10, verbose_name='所在线程组类型'),
        ),
    ]
