# Generated by Django 3.0.8 on 2020-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0019_auto_20200903_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxthreadgroupchildren',
            name='child_thread',
            field=models.CharField(choices=[('thread', '普通线程组'), ('setup', 'setup线程组'), ('teardown', 'setup线程组')], default='thread', max_length=10, verbose_name='所在线程组类型'),
        ),
        migrations.AlterField(
            model_name='jmxthreadgroupchildren',
            name='child_type',
            field=models.CharField(choices=[('sampler', 'http请求'), ('csv', 'CSV数据文件设置'), ('thread', '普通线程组信息')], default='sampler', max_length=10, verbose_name='子类的类型'),
        ),
    ]
