# Generated by Django 3.0.8 on 2020-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0020_auto_20200911_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JmxThreadGroupChildren',
            new_name='JmxThreadGroup',
        ),
    ]
