# Generated by Django 3.0.8 on 2020-09-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0022_jmxs_thread_base_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplersChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='子元素名称')),
                ('child_type', models.CharField(choices=[('header', '请求头'), ('rsp_assert', '响应断言'), ('json_assert', 'json断言'), ('re_extract', '正则提取器'), ('json_extract', 'json提取器'), ('beanshell_start', 'beanshell前置处理器'), ('beanshell_end', 'beanshell后置处理器')], default='header', max_length=20, verbose_name='子元素类型')),
                ('child_info', models.TextField(max_length=1000, verbose_name='子元素信息')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('sampler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmxs.JmxThreadGroup')),
            ],
        ),
    ]
