# Generated by Django 3.0.8 on 2020-09-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0023_samplerschild'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplersChild',
            new_name='SamplersChildren',
        ),
    ]
