# Generated by Django 3.0.8 on 2020-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0024_auto_20200914_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmxthreadgroup',
            name='child_type',
            field=models.CharField(choices=[('sampler', 'http请求'), ('csv', 'CSV数据文件设置')], default='sampler', max_length=10, verbose_name='子类的类型'),
        ),
    ]
