# Generated by Django 3.0.8 on 2020-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0025_auto_20200914_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jmxthreadgroup',
            options={'verbose_name': '线程组子元素信息', 'verbose_name_plural': '线程组子元素信息'},
        ),
        migrations.AlterModelOptions(
            name='samplerschildren',
            options={'verbose_name': 'sampler子元素信息', 'verbose_name_plural': 'sampler子元素信息'},
        ),
        migrations.AlterUniqueTogether(
            name='samplerschildren',
            unique_together={('sampler', 'child_name')},
        ),
    ]
