# Generated by Django 3.0.8 on 2020-09-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0026_auto_20200914_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplerschildren',
            unique_together={('sampler', 'child_name', 'child_type')},
        ),
    ]
