# Generated by Django 3.0.8 on 2020-09-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0027_auto_20200914_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplerschildren',
            unique_together=set(),
        ),
    ]
