# Generated by Django 3.0.8 on 2020-08-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0010_auto_20200813_1420'),
        ('tasks', '0008_auto_20200821_1433'),
        ('jtls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JtlsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtl_url', models.CharField(default='', max_length=100, verbose_name='单个jtl存放地址')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskFlow', verbose_name='task任务流水表')),
                ('jmx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmxs.Jmxs', verbose_name='关联的jmx的id')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks', verbose_name='关联的任务id')),
            ],
            options={
                'verbose_name': 'jtl详情表',
                'verbose_name_plural': 'jtl详情表',
            },
        ),
    ]
