# Generated by Django 3.0.8 on 2020-08-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmxs', '0011_auto_20200823_1401'),
        ('jtls', '0002_jtlsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtlsdetails',
            name='jmx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmxs.Jmxs', verbose_name='关联的jmx的id'),
        ),
    ]
