# Generated by Django 3.0.8 on 2020-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtls', '0004_jtlstocsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtlstocsv',
            name='average_req',
            field=models.CharField(max_length=100, verbose_name='平均值'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='error_rate',
            field=models.CharField(max_length=100, verbose_name='异常比例'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='line90_req',
            field=models.CharField(max_length=100, verbose_name='90%百分位'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='line95_req',
            field=models.CharField(max_length=100, verbose_name='95%百分位'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='line99_req',
            field=models.CharField(max_length=100, verbose_name='99%百分位'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='max_req',
            field=models.CharField(max_length=100, verbose_name='最大值'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='median_req',
            field=models.CharField(max_length=100, verbose_name='中位数'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='min_req',
            field=models.CharField(max_length=100, verbose_name='最小值'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='recieved_per',
            field=models.CharField(max_length=100, verbose_name='每秒从服务器端接收到的数据量'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='tps',
            field=models.CharField(max_length=100, verbose_name='吞吐量'),
        ),
    ]
