# Generated by Django 3.0.8 on 2020-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtls', '0005_auto_20200824_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtlstocsv',
            name='error_rate',
            field=models.FloatField(max_length=100, verbose_name='异常比例'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='recieved_per',
            field=models.FloatField(max_length=100, verbose_name='每秒从服务器端接收到的数据量'),
        ),
        migrations.AlterField(
            model_name='jtlstocsv',
            name='tps',
            field=models.FloatField(max_length=100, verbose_name='吞吐量'),
        ),
    ]
