# Generated by Django 3.0.8 on 2020-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtls', '0007_auto_20200824_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtlsdetails',
            name='jtl_url',
            field=models.CharField(default='', max_length=500, verbose_name='单个jtl存放地址'),
        ),
        migrations.AlterField(
            model_name='jtlssummary',
            name='jtl_url',
            field=models.CharField(max_length=500, verbose_name='生成的汇总的jtl地址'),
        ),
    ]
