# Generated by Django 3.0.8 on 2020-08-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtls', '0008_auto_20200824_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JtlsToCSV',
        ),
    ]
