# Generated by Django 3.0.8 on 2020-08-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtls', '0009_delete_jtlstocsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JtlsDetails',
        ),
    ]
