# Generated by Django 3.0.8 on 2020-08-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uersparams',
            options={'verbose_name': '用户添加的变量', 'verbose_name_plural': '用户添加的变量'},
        ),
        migrations.AlterUniqueTogether(
            name='uersparams',
            unique_together={('env', 'param_name')},
        ),
    ]
