# Generated by Django 3.0.8 on 2020-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_auto_20200828_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='uersparams',
            name='param_content',
            field=models.CharField(default='', max_length=1000, verbose_name='变量备注'),
        ),
    ]
