# Generated by Django 3.0.8 on 2020-09-01 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('params', '0003_uersparams_param_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uersparams',
            unique_together={('user', 'env', 'param_name')},
        ),
    ]
