# Generated by Django 3.0.8 on 2020-08-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0010_auto_20200823_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.CharField(max_length=100, verbose_name='报告地址')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskFlow', verbose_name='流水id')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks', verbose_name='关联的任务id')),
            ],
            options={
                'verbose_name': '报告表',
                'verbose_name_plural': '报告表',
            },
        ),
    ]
